version: '3'

services:
    app:
        build: ./apps/dns-portal
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./dockerfiles/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www
            - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - laravel
        depends_on:
            - app
            - mysql

    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dns_portal:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    dns_portal:
