version: '3'

services:
    laravel:
        build: ./apps/dns-portal
        volumes:
            - ./apps/dns-portal:/var/www
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        networks:
            - app-network

    express:
        build: ./apps/ssh-server
        volumes:
            - ./apps/ssh-server:/app
        networks:
            - app-network

    nginx:
        image: nginx:latest
        ports:
            - '8080:80'
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel
            - express
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - '3306:3306'
        networks:
            - app-network

volumes:
    mysql-data:

networks:
    app-network:
        driver: bridge
