import { ITheme } from '@xterm/xterm';

export type IXTerminal = {
    name: string;
    theme: ITheme;
};

export const defaultTheme = {
    foreground: '#f8f8f2',
    background: '#282a36',
    cursor: '#f8f8f2',
    selectionBackground: '#44475a',
    selectionForeground: '#f8f8f2',
    selectionInactiveBackground: '#44475a',
    black: '#282a36',
    red: '#ff5555',
    green: '#50fa7b',
    yellow: '#f1fa8c',
    blue: '#bd93f9',
    magenta: '#ff79c6',
    cyan: '#8be9fd',
    white: '#f8f8f2',
    brightBlack: '#6272a4',
    brightRed: '#ff6e6e',
    brightGreen: '#69ff94',
    brightYellow: '#ffffa5',
    brightBlue: '#d6acff',
    brightMagenta: '#ff92df',
    brightCyan: '#a4ffff',
    brightWhite: '#ffffff'
};
const themes: IXTerminal[] = [
    {
        name: 'Default',
        theme: defaultTheme
    },
    {
        name: 'One Dark',
        theme: {
            foreground: '#abb2bf',
            background: '#282c34',
            cursor: '#528bff',
            selectionBackground: '#3e4451',
            selectionForeground: '#abb2bf',
            selectionInactiveBackground: '#3e4451',
            black: '#282c34',
            red: '#e06c75',
            green: '#98c379',
            yellow: '#e5c07b',
            blue: '#61afef',
            magenta: '#c678dd',
            cyan: '#56b6c2',
            white: '#dcdfe4',
            brightBlack: '#282c34',
            brightRed: '#e06c75',
            brightGreen: '#98c379',
            brightYellow: '#e5c07b',
            brightBlue: '#61afef',
            brightMagenta: '#c678dd',
            brightCyan: '#56b6c2',
            brightWhite: '#dcdfe4'
        }
    },
    // Add light themes here
    {
        name: 'Light',
        theme: {
            foreground: '#000000',
            background: '#ffffff',
            cursor: '#000000',
            selectionBackground: '#ffffff',
            selectionForeground: '#000000',
            selectionInactiveBackground: '#ffffff',
            black: '#000000',
            red: '#ff0000',
            green: '#00ff00',
            yellow: '#ffff00',
            blue: '#0000ff',
            magenta: '#ff00ff',
            cyan: '#00ffff',
            white: '#ffffff',
            brightBlack: '#808080',
            brightRed: '#ff0000',
            brightGreen: '#00ff00',
            brightYellow: '#ffff00',
            brightBlue: '#0000ff',
            brightMagenta: '#ff00ff',
            brightCyan: '#00ffff',
            brightWhite: '#ffffff'
        }
    },
    {
        name: 'Solarized Light',
        theme: {
            foreground: '#657b83',
            background: '#fdf6e3',
            cursor: '#657b83',
            selectionBackground: '#073642',
            selectionForeground: '#657b83',
            selectionInactiveBackground: '#073642',
            black: '#073642',
            red: '#dc322f',
            green: '#859900',
            yellow: '#b58900',
            blue: '#268bd2',
            magenta: '#d33682',
            cyan: '#2aa198',
            white: '#eee8d5',
            brightBlack: '#002b36',
            brightRed: '#cb4b16',
            brightGreen: '#586e75',
            brightYellow: '#657b83',
            brightBlue: '#839496',
            brightMagenta: '#6c71c4',
            brightCyan: '#93a1a1',
            brightWhite: '#fdf6e3'
        }
    },
    {
        name: 'Solarized Dark',
        theme: {
            foreground: '#839496',
            background: '#002b36',
            cursor: '#839496',
            selectionBackground: '#073642',
            selectionForeground: '#839496',
            selectionInactiveBackground: '#073642',
            black: '#073642',
            red: '#dc322f',
            green: '#859900',
            yellow: '#b58900',
            blue: '#268bd2',
            magenta: '#d33682',
            cyan: '#2aa198',
            white: '#eee8d5',
            brightBlack: '#002b36',
            brightRed: '#cb4b16',
            brightGreen: '#586e75',
            brightYellow: '#657b83',
            brightBlue: '#839496',
            brightMagenta: '#6c71c4',
            brightCyan: '#93a1a1',
            brightWhite: '#fdf6e3'
        }
    },
    {
        name: 'Material Darker',
        theme: {
            foreground: '#c5c8c6',
            background: '#1d1f21',
            cursor: '#c5c8c6',
            selectionBackground: '#373b41',
            selectionForeground: '#c5c8c6',
            selectionInactiveBackground: '#373b41',
            black: '#282a2e',
            red: '#a54242',
            green: '#8c9440',
            yellow: '#de935f',
            blue: '#5f819d',
            magenta: '#85678f',
            cyan: '#5e8d87',
            white: '#707880',
            brightBlack: '#373b41',
            brightRed: '#cc6666',
            brightGreen: '#b5bd68',
            brightYellow: '#f0c674',
            brightBlue: '#81a2be',
            brightMagenta: '#b294bb',
            brightCyan: '#8abeb7',
            brightWhite: '#c5c8c6'
        }
    },
    {
        name: 'Material Lighter',
        theme: {
            foreground: '#383a42',
            background: '#fafafa',
            cursor: '#383a42',
            selectionBackground: '#f0f0f0',
            selectionForeground: '#383a42',
            selectionInactiveBackground: '#f0f0f0',
            black: '#fafafa',
            red: '#e45649',
            green: '#50a14f',
            yellow: '#986801',
            blue: '#4078f2',
            magenta: '#a626a4',
            cyan: '#0184bc',
            white: '#383a42',
            brightBlack: '#a0a1a7',
            brightRed: '#e45649',
            brightGreen: '#50a14f',
            brightYellow: '#986801',
            brightBlue: '#4078f2',
            brightMagenta: '#a626a4',
            brightCyan: '#0184bc',
            brightWhite: '#383a42'
        }
    },
    {
        name: 'Nord',
        theme: {
            foreground: '#d8dee9',
            background: '#2e3440',
            cursor: '#d8dee9',
            selectionBackground: '#3b4252',
            selectionForeground: '#d8dee9',
            selectionInactiveBackground: '#3b4252',
            black: '#3b4252',
            red: '#bf616a',
            green: '#a3be8c',
            yellow: '#ebcb8b',
            blue: '#81a1c1',
            magenta: '#b48ead',
            cyan: '#88c0d0',
            white: '#e5e9f0',
            brightBlack: '#4c566a',
            brightRed: '#bf616a',
            brightGreen: '#a3be8c',
            brightYellow: '#ebcb8b',
            brightBlue: '#81a1c1',
            brightMagenta: '#b48ead',
            brightCyan: '#8fbcbb',
            brightWhite: '#eceff4'
        }
    },
    {
        name: 'Nord Light',
        theme: {
            foreground: '#2e3440',
            background: '#eceff4',
            cursor: '#2e3440',
            selectionBackground: '#d8dee9',
            selectionForeground: '#2e3440',
            selectionInactiveBackground: '#d8dee9',
            black: '#eceff4',
            red: '#bf616a',
            green: '#a3be8c',
            yellow: '#ebcb8b',
            blue: '#81a1c1',
            magenta: '#b48ead',
            cyan: '#88c0d0',
            white: '#4c566a',
            brightBlack: '#d8dee9',
            brightRed: '#bf616a',
            brightGreen: '#a3be8c',
            brightYellow: '#ebcb8b',
            brightBlue: '#81a1c1',
            brightMagenta: '#b48ead',
            brightCyan: '#8fbcbb',
            brightWhite: '#eceff4'
        }
    },
    {
        name: 'Gruvbox Dark',
        theme: {
            foreground: '#ebdbb2',
            background: '#282828',
            cursor: '#ebdbb2',
            selectionBackground: '#3c3836',
            selectionForeground: '#ebdbb2',
            selectionInactiveBackground: '#3c3836',
            black: '#282828',
            red: '#cc241d',
            green: '#98971a',
            yellow: '#d79921',
            blue: '#458588',
            magenta: '#b16286',
            cyan: '#689d6a',
            white: '#a89984',
            brightBlack: '#928374',
            brightRed: '#fb4934',
            brightGreen: '#b8bb26',
            brightYellow: '#fabd2f',
            brightBlue: '#83a598',
            brightMagenta: '#d3869b',
            brightCyan: '#8ec07c',
            brightWhite: '#ebdbb2'
        }
    },
    {
        name: 'Gruvbox Light',
        theme: {
            foreground: '#3c3836',
            background: '#fbf1c7',
            cursor: '#3c3836',
            selectionBackground: '#ebdbb2',
            selectionForeground: '#3c3836',
            selectionInactiveBackground: '#ebdbb2',
            black: '#fbf1c7',
            red: '#cc241d',
            green: '#98971a',
            yellow: '#d79921',
            blue: '#458588',
            magenta: '#b16286',
            cyan: '#689d6a',
            white: '#928374',
            brightBlack: '#3c3836',
            brightRed: '#9d0006',
            brightGreen: '#79740e',
            brightYellow: '#b57614',
            brightBlue: '#076678',
            brightMagenta: '#8f3f71',
            brightCyan: '#427b58',
            brightWhite: '#504945'
        }
    }
];

export default themes;
